[package]
name = "_p5e4"
version = "0.1.0"
edition = "2024"

[dependencies]
error_proc_macro = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
cargo-tarpaulin = "0.32.7"